---
abstract: 'easily automate human choices'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test2::V0: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.64, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-choices
no_index:
  directory:
    - t
    - inc
requires:
  DBD::SQLite: '0'
  DBIx::RunSQL: '0'
  Mojo::JSON: '0'
  Mojo::SQLite: '0'
  Mojolicious::Lite: '0'
  Moo: '2'
  POSIX: '0'
  PerlX::Maybe: '0'
  experimental: '0.032'
  perl: '5.020'
resources:
  bugtracker: https://github.com/Corion/App-choices/issues
  license: https://dev.perl.org/licenses/
  repository: git://github.com/Corion/App-choices.git
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
